authentication/urls.py
from django.urls import path
from .views import login_view, register_user
from django.contrib.auth.views import LogoutView

app_name ="authen"
urlpatterns = [
    path('signin/', login_view, name="login"),
    path('signup/', register_user, name="register"),
    path('logout/', LogoutView.as_view(), name="logout"),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
     path('', include('authentication.urls', namespace='authen')),
    
]

templates/accounts/login.html
{% extends '../layout/base.html' %} {% load static %} {% block css %} {% endblock css %} {% block body %}



<body class="main-layout inner_page mt-4">
    <!-- loader  -->
    <div class="loader_bg">
        <div class="loader"><img src="{% static 'upload/twi16.png' %}" alt="#" /></div>
    </div>
    <!-- end loader -->
    <!-- header -->
    {% include 'include/nav.html' %}
    <!-- end header inner -->
    <!-- blog -->
    <div class="row justify-content-center form-bg-image" data-background-lg="/static/assets/img/illustrations/signin.svg">
        <div class="col-4 d-flex align-items-center justify-content-center">
            <div class="bg-white shadow border-0 rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                <div class="text-center text-md-center mb-4 mt-md-4">
                    <h1 class="mb-0 h1">
                        USER LOGIN
                    </h1>
                    <br />
                    <p>
                        {% if msg %} {{ msg | safe }} {% else %} Add your credentials {% endif %}
                    </p>
                </div>
                <form method="post" action="" class="ml-6 p-9">

                    {% csrf_token %} {{form.as_p}}
                    <div class="d-grid">
                        <button type="submit" name="login" class="btn btn-gray-800">Sign IN</button>
                    </div>
                </form>
                <br />


                <div class="d-flex justify-content-center align-items-center mt-4">
                    <span class="fw-normal">
                        Not registered?
                        <a href="{% url 'authen:register' %}" class="fw-bold">Create account</a>
                    </span>
                </div>
            </div>
        </div>
    </div>
    {% include 'include/scripts.html' %}

</body>
{% endblock body %}

templates/accounts/register.html
{% extends '../layout/base.html' %} {% load static %} {% block css %} {% endblock css %} {% block body %}

<body class="main-layout inner_page mt-45">
    <!-- loader  -->
    <div class="loader_bg">
        <div class="loader"><img src="{% static 'images/loading_2.gif' %}" alt="#" /></div>
    </div>
    <!-- end loader -->
    <!-- header -->
    {% include 'include/nav.html' %}
    <!-- end header inner -->
    <!-- blog -->
    <div class="row justify-content-center form-bg-image" data-background-lg="/static/assets/img/illustrations/signin.svg">
        <div class="col-4 d-flex align-items-center justify-content-center">
            <div class="bg-white shadow border-0 rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                <div class="text-center text-md-center mb-4 mt-4">
                    <h1 class="mb-0 h3">
                        Register HERE
                    </h1>
                    <br />
                    <p>
                        {% if msg %} {{ msg | safe }} {% else %} Add your credentials {% endif %}
                    </p>
                </div>
                <form method="post" action="" class="ml-6 p-9 ">

                    {% csrf_token %} {{form.as_p}}
                    <div class="d-grid">
                        <button type="submit" name="login" class="btn btn-gray-800">Register</button>
                    </div>
                </form>
                <br />


                <div class="d-flex justify-content-center align-items-center mt-4">
                    <span class="fw-normal">
                        Not registered?
                        <a href="{% url 'authen:register' %}" class="fw-bold">Create account</a>
                    </span>
                </div>
            </div>
        </div>
    </div>
    {% include 'include/scripts.html' %}

</body>
{% endblock body %}