authentication/urls.py
from django.urls import path
from .views import login_view, register_user
from django.contrib.auth.views import LogoutView

app_name ="authen"
urlpatterns = [
    path('signin/', login_view, name="login"),
    path('signup/', register_user, name="register"),
    path('logout/', LogoutView.as_view(), name="logout"),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
     path('', include('authentication.urls', namespace='authen')),
    
]

templates/include/footer.html
{% load static %}
<footer class="footer ">
    <div class="container ">
        <div class="row ">
            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 ">
                <div class="widget ">


                    <!-- end blog-list -->
                </div>
                <!-- end widget -->
            </div>
            <!-- end col -->



        </div>
    </div>
    <!-- end blog-list -->
    <!-- end col -->

    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 ">
        <div class="widget ">

            <!-- end link-widget -->
        </div>
        <!-- end widget -->
    </div>
    <!-- end col -->
    </div>
    <!-- end row -->

    <div class="row ">
        <div class="col-md-12 text-center ">
            <br>
            <br>
            <div class="blog-meta big-meta text-center ">
                <div class="post-sharing ">

                    <ul class="list-inline ">
                        <li>
                            <a href="https://www.facebook.com/panditabhishek.dwivedi.9" class=" fb-button btn btn-primary "><i
                                                class="fa fa-facebook "></i> <span class="down-mobile ">
                                                Facebook</span></a></li>
                        <li><a href=" https://twitter.com/home" class="tw-button btn btn-primary "><i
                                                class="fa fa-twitter "></i> <span class="down-mobile ">
                                                Twitter</span></a></li>
                        <li><a href="# " class="gp-button btn btn-primary "><i
                                                class="fa fa-google-plus "></i></a></li>
                    </ul>
                </div>
                <div class="copyright ">@copyright:2022 DIGININJA <a href="http://html.design ">HTML Design</a>.
                </div>
            </div>
        </div>
    </div>
    <!-- end container -->
</footer>

templates/include/nav.html
{% load static %}
<header class="market-header header">
    <div class="container-fluid">
        <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="marketing-index.html"><img src="{% static 'upload/twi5.jpeg' %} " alt=""></a>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/service">Service</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/contact">contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/about">About</a>
                    </li>


                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authen:logout' %}">Signout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/signin">Login</a>
                    </li>
                    {% endif %}

                </ul>
                <form class="form-inline" method="POST" action="/search/">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" type="text" placeholder="write your query" name="query">
                    <button class=" btn btn-outline-success my-2 my-sm-0 " type="submit ">Search</button>
                </form>
            </div>
        </nav>
    </div>
    <!-- end container-fluid -->
</header>

templates/include/scripts.html
{% load static %}
<script src="js/jquery.min.js">
</script>
<script src="js/tether.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/animate.js"></script>
<script src="js/custom.js"></script>